spring.application.name=movie-info-service
server.port=8082

api.key=b0af84324ea41ca39f4311c9156e94e3
# mongodb configs
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=movie_info_db

# cache configs
movie.cache.enabled=true
movie.cache.max-size=10000